[package]
name = "tplay"
version = "1.0.0"
edition = "2021"
authors = ["Max Curzi <massimiliano.curzi@gmail.com>"]
description = "A terminal based media player that visualizes images and videos as ASCII art."
repository = "www.github.com/maxcurzi/tplay"
license-file = "LICENSE"
readme = "README.md"
keywords = ["media-player", "ASCII-art", "terminal", "youtube", "video"]
categories = [
    "command-line-utilities",
    "multimedia",
    "multimedia::video",
    "multimedia::images",
]
exclude = [
    ".github/",
    ".vscode/",
    ".gitignore",
    " Cargo.lock",
    " Cargo.toml.orig",
    " Makefile.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
crossterm = "0.26.1"
gif = "0.12.0"
image = "0.24.6"
opencv = "0.78.2"
thiserror = "1.0.40"
fast_image_resize = "2.7.0"
youtube_dl = "0.8.0"
tempfile = "3.5.0"
url = "2.3.1"

[dev-dependencies]
reqwest = { version = "0.11.6", features = ["blocking"] }

[[bin]]
name = "tplay"
path = "src/main.rs"
