[package]
name = "tplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
crossterm = "0.26.1"
gif = "0.12.0"
image = "0.24.6"
ndarray = "0.15.6"
opencv = "0.78.2"
thiserror = "1.0.40"
flame = "0.2.2"
flamer = "0.3"
fast_image_resize = "2.7.0"
youtube_dl = "0.8.0"
tempfile = "3.5.0"
url = "2.3.1"
rodio = "0.17.1"
ffmpeg-next = "6.0.0"

[dev-dependencies]
reqwest = { version = "0.11.6", features = ["blocking"] }

[[bin]]
name = "tplay"
path = "src/main.rs"
