[tasks.build-win]
command = "cross build --target x86_64-pc-windows-gnu --release"

[tasks.build-linux]
command = "cross build --target x86_64-unknown-linux-gnu --release"

[tasks.build-mac]
command = "cross build --target x86_64-apple-darwin --release"

[tasks.build-arm]
command = "cross build --target aarch64-unknown-linux-gnu --release"

[tasks.package]
command = "tar -czvf tplay.tar.gz target/x86_64-pc-windows-gnu/release/tplay.exe target/x86_64-unknown-linux-gnu/release/tplay target/x86_64-apple-darwin/release/tplay target/aarch64-unknown-linux-gnu/release/tplay"
dependencies = ["build-win", "build-linux", "build-mac", "build-arm"]
